---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  SSM sample
Resources:
  CustomApplications:
    Type: "AWS::SSM::Document"
    Properties:
      DocumentType: "Command"
      Content:
        schemaVersion: "1.2"
        description: "Get Instance Metadata"
        runtimeConfig:
          aws:runShellScript:
            properties:
              - id: 0.aws:runShellScript
                runCommand:
                  - REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed -e "s/.$//g")
                  - INSTANCEID=$(/usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id)
                  - ITEMS=$(curl https://raw.githubusercontent.com/devinacosta/ssm_inventry_resources/master/instancemeta.sh | bash)
                  - aws ssm put-inventory  --instance-id "${INSTANCEID}"  --items "$(echo ${ITEMS})"  --region "${REGION}"
                workingDirectory: "/"
                timeoutSeconds: "300"
